SECTORS = [
    ("Defense", "#f8ec20"),
    ("Economy & Employment", "#b0b0b8"),
    ("Education", "#70f828"),
    ("Emergency Services, Public Safety & Law Enforcement", "#7070fc"),
    ("Energy", "#a82814"),
    ("Food & Agriculture", "#fc4848"),
    ("Housing", "#fc74ec"),
    ("Humanities & the Arts", "#e1a886"),
    ("Immigration", "#5d0483"),
    ("Infrastructure", "#1c38ac"),
    ("International Development", "#b82cd0"),
    ("Natural Resources, Environment & Public Lands", "#208800"),
    ("Overarching", "#ac581c"),
    ("Public Health & Healthcare", "#f8a850"),
    ("Research & Academic Research", "#3cd4e4"),
    ("Social Services", "#68605c"),
]

ACTION_TYPES = [
    ("Contract Terminated for Convenience", "cuts"),
    ("Federal Worker Resigned", "cuts"),
    ("Federal Workers Fired", "cuts"),
    ("Federal Workers Put on Leave/In Limbo", "cuts"),
    ("Funding Frozen/Paused/Cancelled", "cuts"),
    ("Government Building Disposition", "cuts"),
    ("Hiring Freeze", "cuts"),
    ("Lease Terminated", "cuts"),
    ("Other Federal Cut", "cuts"),
    ("Program Paused/Under Review/Cancelled", "cuts"),
    ("Fed Workers Rehired/Possible Rehiring", "adds"),
    ("Funding Unfrozen", "adds"),
    ("Lease Cancellation Rescinded", "adds"),
    ("New Program/Service/Benefit", "adds"),
    ("Other Federal Add", "adds"),
    ("Industry Response to Cut", "responses"),
    ("Judicial Action", "responses"),
    ("Local Response to Cuts", "responses"),
    ("NGO Response to Cut", "responses"),
    ("State Responses to Cuts", "responses"),
]
